language: minimal

dist: bionic
sudo: required
cache: false

addons:
  apt:
    sources:
      - sourceline: 'deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-8 main'
      - sourceline: 'deb-src http://apt.llvm.org/bionic/ llvm-toolchain-bionic-8 main'
      - key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
    packages:
      - clang-8
      - llvm-8
      - llvm-8-dev
      - lld-8
      - python3
      - python3-setuptools
      - python3-wheel
      - python3-pip
      - ninja-build
      - make
      - wget
      - tar

      
install:
  - sudo pip3 install meson
  # Install a recent version of cmake for -B
  - CMAKE_VERSION=3.15.2
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      CMAKE_URL="https://cmake.org/files/v${CMAKE_VERSION%.[0-9]}/cmake-${CMAKE_VERSION}-Linux-x86_64.tar.gz"
      mkdir cmake && travis_retry wget --no-check-certificate -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
      export PATH=${TRAVIS_BUILD_DIR}/cmake/bin:${PATH}
    else
      brew install cmake || brew upgrade cmake
    fi
  - cmake --version

  # Install linkle
  - LINKLE_VERSION=v0.2.7
  - wget https://github.com/MegatonHammer/linkle/releases/download/$LINKLE_VERSION/linkle-$LINKLE_VERSION-x86_64-unknown-linux-musl.tar.gz
  - tar -xvf linkle-$LINKLE_VERSION-x86_64-unknown-linux-musl.tar.gz

  # Correctly map the version of LLVM at the system level
  - "sudo update-alternatives --install /usr/bin/clang clang /usr/bin/clang++-8 200 \
    --slave /usr/bin/asan_symbolize asan_symbolize /usr/bin/asan_symbolize-8 \
    --slave /usr/bin/clang++ clang++ /usr/bin/clang++-8 \
    --slave /usr/bin/clang-cpp clang-cpp /usr/bin/clang-cpp-8"
  - "sudo update-alternatives --install /usr/bin/llvm-config llvm-config /usr/bin/llvm-config-8 200 \
    --slave /usr/bin/bugpoint bugpoint /usr/bin/bugpoint-8 \
    --slave /usr/bin/llc llc /usr/bin/llc-8 \
    --slave /usr/bin/llvm-PerfectShuffle llvm-PerfectShuffle /usr/bin/llvm-PerfectShuffle-8 \
    --slave /usr/bin/llvm-ar llvm-ar /usr/bin/llvm-ar-8 \
    --slave /usr/bin/llvm-as llvm-as /usr/bin/llvm-as-8 \
    --slave /usr/bin/llvm-bcanalyzer llvm-bcanalyzer /usr/bin/llvm-bcanalyzer-8 \
    --slave /usr/bin/llvm-c-test llvm-c-test /usr/bin/llvm-c-test-8 \
    --slave /usr/bin/llvm-cat llvm-cat /usr/bin/llvm-cat-8 \
    --slave /usr/bin/llvm-cfi-verify llvm-cfi-verify /usr/bin/llvm-cfi-verify-8 \
    --slave /usr/bin/llvm-cov llvm-cov /usr/bin/llvm-cov-8 \
    --slave /usr/bin/llvm-cvtres llvm-cvtres /usr/bin/llvm-cvtres-8 \
    --slave /usr/bin/llvm-cxxdump llvm-cxxdump /usr/bin/llvm-cxxdump-8 \
    --slave /usr/bin/llvm-cxxfilt llvm-cxxfilt /usr/bin/llvm-cxxfilt-8 \
    --slave /usr/bin/llvm-diff llvm-diff /usr/bin/llvm-diff-8 \
    --slave /usr/bin/llvm-dis llvm-dis /usr/bin/llvm-dis-8 \
    --slave /usr/bin/llvm-dlltool llvm-dlltool /usr/bin/llvm-dlltool-8 \
    --slave /usr/bin/llvm-dsymutil llvm-dsymutil /usr/bin/llvm-dsymutil-8 \
    --slave /usr/bin/llvm-dwarfdump llvm-dwarfdump /usr/bin/llvm-dwarfdump-8 \
    --slave /usr/bin/llvm-dwp llvm-dwp /usr/bin/llvm-dwp-8 \
    --slave /usr/bin/llvm-extract llvm-extract /usr/bin/llvm-extract-8 \
    --slave /usr/bin/llvm-lib llvm-lib /usr/bin/llvm-lib-8 \
    --slave /usr/bin/llvm-link llvm-link /usr/bin/llvm-link-8 \
    --slave /usr/bin/llvm-lto llvm-lto /usr/bin/llvm-lto-8 \
    --slave /usr/bin/llvm-lto2 llvm-lto2 /usr/bin/llvm-lto2-8 \
    --slave /usr/bin/llvm-mc llvm-mc /usr/bin/llvm-mc-8 \
    --slave /usr/bin/llvm-mcmarkup llvm-mcmarkup /usr/bin/llvm-mcmarkup-8 \
    --slave /usr/bin/llvm-modextract llvm-modextract /usr/bin/llvm-modextract-8 \
    --slave /usr/bin/llvm-mt llvm-mt /usr/bin/llvm-mt-8 \
    --slave /usr/bin/llvm-nm llvm-nm /usr/bin/llvm-nm-8 \
    --slave /usr/bin/llvm-objcopy llvm-objcopy /usr/bin/llvm-objcopy-8 \
    --slave /usr/bin/llvm-objdump llvm-objdump /usr/bin/llvm-objdump-8 \
    --slave /usr/bin/llvm-opt-report llvm-opt-report /usr/bin/llvm-opt-report-8 \
    --slave /usr/bin/llvm-pdbutil llvm-pdbutil /usr/bin/llvm-pdbutil-8 \
    --slave /usr/bin/llvm-profdata llvm-profdata /usr/bin/llvm-profdata-8 \
    --slave /usr/bin/llvm-ranlib llvm-ranlib /usr/bin/llvm-ranlib-8 \
    --slave /usr/bin/llvm-rc llvm-rc /usr/bin/llvm-rc-8 \
    --slave /usr/bin/llvm-readelf llvm-readelf /usr/bin/llvm-readelf-8 \
    --slave /usr/bin/llvm-readobj llvm-readobj /usr/bin/llvm-readobj-8 \
    --slave /usr/bin/llvm-rtdyld llvm-rtdyld /usr/bin/llvm-rtdyld-8 \
    --slave /usr/bin/llvm-size llvm-size /usr/bin/llvm-size-8 \
    --slave /usr/bin/llvm-split llvm-split /usr/bin/llvm-split-8 \
    --slave /usr/bin/llvm-stress llvm-stress /usr/bin/llvm-stress-8 \
    --slave /usr/bin/llvm-strings llvm-strings /usr/bin/llvm-strings-8 \
    --slave /usr/bin/llvm-symbolizer llvm-symbolizer /usr/bin/llvm-symbolizer-8 \
    --slave /usr/bin/llvm-tblgen llvm-tblgen /usr/bin/llvm-tblgen-8 \
    --slave /usr/bin/llvm-xray llvm-xray /usr/bin/llvm-xray-8 \
    --slave /usr/bin/obj2yaml obj2yaml /usr/bin/obj2yaml-8 \
    --slave /usr/bin/opt opt /usr/bin/opt-8 \
    --slave /usr/bin/sanstats sanstats /usr/bin/sanstats-8 \
    --slave /usr/bin/verify-uselistorder verify-uselistorder /usr/bin/verify-uselistorder-8 \
    --slave /usr/bin/yaml2obj yaml2obj /usr/bin/yaml2obj-8"
  - sudo update-alternatives --install /usr/bin/ld.lld ld.lld /usr/bin/ld.lld-8 200
  - sudo update-alternatives --install /usr/bin/cc cc /usr/bin/clang 100
  - sudo update-alternatives --install /usr/bin/c++ c++ /usr/bin/clang++ 100

  # Because Travis ship with an old version of llvm, we remove it to avoid conflicts...
  - sudo rm -rf /usr/local/clang-7.0.0/

script:
  - sudo PATH="${TRAVIS_BUILD_DIR}/cmake/bin:$TRAVIS_BUILD_DIR:$PATH" HYDROSPHERE=/opt/hydrosphere make prepare-launch
